services:
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    expose:
      - "3307"
    environment:
      - MYSQL_USER=ActivityUser
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_DATABASE=activity_db
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"