apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: activity
  template:
    metadata:
      labels:
        app: activity
    spec:
      containers:
        - env:
            - name: DISCOVERY_HOST
              value: discovery
            - name: MYSQL_DATABASE
              value: activity_db
            - name: MYSQL_FINANCIAL_HOST
              value: mysql_financial
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PASSWORD
              value: activity_password
            - name: MYSQL_USER
              value: activity_user
            - name: PORT_API
              value: "8080"
            - name: PORT_DB
              value: "3306"
            - name: PORT_DISCOVERY
              value: "8761"
            - name: PORT_RABBITMQ
              value: "5672"
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PASS
              value: guest
            - name: RABBITMQ_USER
              value: guest
          image: dockjoep/tartaros-services:activity
          name: activity
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: activity-service
  labels:
    app: activity-service
spec:
  selector:
    app: activity
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080