apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: activity_db
            - name: MYSQL_PASSWORD
              value: activity_password
            - name: MYSQL_ROOT_PASSWORD
              value: root_password
            - name: MYSQL_USER
              value: activity_user
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-financial
  labels:
    app: mysql-financial
spec:
  selector:
    matchLabels:
      app: mysql-financial
  template:
    metadata:
      labels:
        app: mysql-financial
    spec:
      containers:
        - name: mysql-financial
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: financial_db
            - name: MYSQL_PASSWORD
              value: financial_password
            - name: MYSQL_ROOT_PASSWORD
              value: root_password
            - name: MYSQL_USER
              value: financial_user
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-financial
  labels:
    app: mysql-financial
spec:
  selector:
    app: mysql-financial
  ports:
    - protocol: TCP
      port: 3306