apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  strategy: {}
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
        - image: dockjoep/tartaros-services:discovery
          name: services-discovery
          ports:
            - containerPort: 8761
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: discovery
  name: discovery
spec:
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  selector:
    app: discovery