apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financial
  template:
    metadata:
      labels:
        app: financial
    spec:
      containers:
        - env:
            - name: DISCOVERY_HOST
              value: discovery
            - name: MYSQL_DATABASE
              value: financial_db
            - name: MYSQL_FINANCIAL_HOST
              value: mysql-financial
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PASSWORD
              value: financial_password
            - name: MYSQL_USER
              value: financial_user
            - name: PORT_API
              value: "8080"
            - name: PORT_DB
              value: "3306"
            - name: PORT_DISCOVERY
              value: "8761"
            - name: PORT_RABBITMQ
              value: "5672"
            - name: RABBITMQ_HOST
              value: rabbitmq
          image: dockjoep/tartaros-services:financial
          name: financial
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always