apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - env:
            - name: DISCOVERY_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DISCOVERY_HOST
            - name: PORT_API
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PORT_API
            - name: PORT_DISCOVERY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PORT_DISCOVERY
          image: dockjoep/tartaros-services:gateway
          name: gateway
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      