apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: google
  name: google
spec:
  replicas: 1
  selector:
    matchLabels:
      app: google
  template:
    metadata:
      labels:
        app: google
    spec:
      containers:
        - env:
            - name: DISCOVERY_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DISCOVERY_HOST
            - name: PORT_API
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PORT_API
            - name: PORT_DISCOVERY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PORT_DISCOVERY
          image: dockjoep/tartaros-services:google
          name: google
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: google-service
  labels:
    app: google-service
spec:
  selector:
    app: google
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080