kubectl apply -f financial.yaml
kubectl apply -f activity.yaml
kubectl apply -f discovery.yaml
kubectl apply -f gateway.yaml
kubectl apply -f activity.yaml
kubectl apply -f rabbitmq.yaml
kubectl apply -f ui.yaml
kubectl apply -f google.yaml
kubectl apply -f auth.yaml
kubectl apply -f secrets.yaml
