apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-activity
  labels:
    app: mysql-activity
spec:
  selector:
    matchLabels:
      app: mysql-activity
  template:
    metadata:
      labels:
        app: mysql-activity
    spec:
      containers:
        - name: mysql-activity
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: activity_db
            - name: MYSQL_PASSWORD
              value: activity_password
            - name: MYSQL_ROOT_PASSWORD
              value: root_password
            - name: MYSQL_USER
              value: activity_user
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-activity
  labels:
    app: mysql-activity
spec:
  selector:
    app: mysql-activity
  ports:
    - protocol: TCP
      port: 3306