apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - env:
            - name: DISCOVERY_HOST
              value: discovery
            - name: MYSQL_FINANCIAL_HOST
              value: mysql_financial
            - name: MYSQL_HOST
              value: mysql
            - name: PORT_API
              value: "8080"
            - name: PORT_DB
              value: "3306"
            - name: PORT_DISCOVERY
              value: "8761"
            - name: PORT_RABBITMQ
              value: "5672"
            - name: RABBITMQ_HOST
              value: rabbitmq
          image: dockjoep/tartaros-services:ui
          name: ui
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  labels:
    app: ui-service
spec:
  selector:
    app: ui
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080