services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    env_file:
      mysql_info.env
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"